[platformio]
default_envs = picopod_rp2040

[env:picopod_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#9c167c6b8aac4f4cfa6d55a0c4e5b848795150c0
board = rpipico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_protocol = picotool
lib_ldf_mode = deep+
build_flags =
    -DPICOPOD_NODE_ID=6
lib_deps =
    jgromes/RadioLib @ 6.6.0
