#ifndef _GEREALSETTINGS_H_
#define _GEREALSETTINGS_H_
#define MAX_PACKET_SIZE (255)
#define MAC_OVERHEAD (4+2+2)
#define LCMM_OVERHEAD (1+2)
#define DTP_OVERHEAD (2+2+2+1+1)
#define DATASIZE_MAC (MAX_PACKET_SIZE - MAC_OVERHEAD)
#define DATASIZE_LCMM (MAX_PACKET_SIZE - LCMM_OVERHEAD - MAC_OVERHEAD)
#define DATASIZE_DTP (MAX_PACKET_SIZE - DTP_OVERHEAD - LCMM_OVERHEAD - MAC_OVERHEAD)
#endif // _GEREALSETTINGS_H_
